tsm_region_id = 13  # North America BCC
tsm_realm_id = 762  # Eranikus
tsm_ah_id = 471     # Eranikus - Alliance AH
tsm_cache_dir = "ah"
blizzard_realm_id = 4800  # US - Eranikus
blizzard_ah_id = 2  # Alliance AH
blizzard_item_cache = "item_ids.pkl"
blizzard_item_reverse_cache = "item_names.pkl"
blizzard_cache_dir = "bliz-ah"
